change-id = 118724
[build]
build-stage = 1

extended = true

tools = [
    "rustfmt",
    "rust-analyzer",
    "rust-analyzer-proc-macro-srv",
]

verbose = 1



[rust]
optimize = true
debug = true
codegen-units = 0

[llvm]
download-ci-llvm = false

