[package]
name = "mimalloc"
version = "0.0.0"
edition = "2021"

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
compiler_builtins = { version = "0.1.0", features = ['rustc-dep-of-std'] }
libc = { version = "0.2.146", default-features = false }

[build-dependencies]
cc = "1.0.69"
